apiVersion: v1
kind: ServiceAccount
metadata:
  name: crds-objects-browser
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crds-objects-browser
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crds-objects-browser
subjects:
- kind: ServiceAccount
  name: crds-objects-browser
  namespace: default
roleRef:
  kind: ClusterRole
  name: crds-objects-browser
  apiGroup: rbac.authorization.k8s.io 